name: Execute backend linters and tests
on: 
  pull_request:
    paths: 
    - 'backend/**'

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Linters
        run: npm run ci

      - name: Run Tests
        run: npm run test
        